# classeur-cv-k8s.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: classeur-cv-deployment
  labels:
    app: classeur-cv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classeur-cv
  template:
    metadata:
      labels:
        app: classeur-cv
    spec:
      containers:
      - name: classeur-cv-container
        image: classeur-cv-app:v1   # Votre image
        imagePullPolicy: Never      # IMPORTANT: Forcer l'utilisation de l'image locale au nœud
        ports:
        - containerPort: 8000
        # MISTRAL_API_KEY est lue depuis .env dans l'image

---

apiVersion: v1
kind: Service
metadata:
  name: classeur-cv-service
  labels:
    app: classeur-cv
spec:
  type: NodePort
  selector:
    app: classeur-cv
  ports:
  - name: http
    protocol: TCP
    port: 8000       # Port interne du service
    targetPort: 8000 # Port du conteneur
    # nodePort: 30080 # Optionnel, laissons K8s choisir pour l'instant